module.exports={
    dev: {
        VUE_APP_APIURL: 'http://website.tsapre.cn',
        VUE_APP_WEBSITE: 'http://website.tsapre.cn',
        VUE_APP_QLWS: 'https://tsa.soboten.com/chat/pc/v2/index.html?sysnum=05dcdaf7a8c2441aa325da0e40ea8b8a',
        VUE_media: 'http://media.tsa.cn/tsa',
        VUE_verify: 'https://v.tsa.cn/',
        VUE_scp: 'http://scp.tsa.cn/',
        VUE_pkulaw: 'https://www.pkulaw.com/',
        VUE_baidu: 'https://xuper.baidu.com/case/econtract',
        VUE_jp: 'http://jp.tsa.cn/dist/page/index',
        VUE_tsa: 'http://usercenter.tsa.cn/login?clientId=700012',
        VUE_registration: 'https://usercenter.tsa.cn/agreement/registration',
        VUE_privacy: 'http://usercenter.tsa.cn/agreement/privacy',
        VUE_ntsc: 'http://www.ntsc.ac.cn/',
        VUE_beidou: 'http://www.beidou.gov.cn/',
        VUE_veer: 'https://www.veer.com/',
        VUE_beian: 'https://beian.miit.gov.cn/#/Integrated/index',
        VUE_APP_USERCENTERUI: 'http://usercenter.tsapre.cn?clientId=700012',
        VUE_APP_ACCOUNT: 'http://account.tsapre.cn/',
        VUE_APP_ACCOUNT_M:'http://account-m.tsapre.cn/',
        VUE_Ev: 'http://ev.tsapre.cn/',
        VUE_icopyright: 'http://ipr.tsapre.cn/',
        VUE_1sign: 'http://pre.1sign.cn/',
        VUE_APP_EMAIL:'http://mail-proof-test.tsa.cn/',
        VUE_APP_ANBEI: 'http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010502045493',
        VUE_APP_HOME: 'http://website-m.tsapre.cn/',
        VUE_APP_LAWCASE: 'http://lawcase.tsatest.cn/'
    },
    test: {
        VUE_APP_USERCENTER:'http://usercenter.tsatest.cn',
        VUE_APP_ACCOUNTUI:'http://account.tsatest.cn',
        VUE_APP_ACCOUNTUI_M:"http://account-m.tsatest.cn",
        VUE_APP_WEBSITE:'http://website.tsatest.cn/',
        VUE_APP_EV:'http://ev.tsatest.cn',
        VUE_APP_SIGN:'http://172.20.0.104:8093',
        VUE_APP_COPYRIGHT:'http://opus.tsatest.cn',
        VUE_APP_EMAIL:'http://mail-proof.tsatest.cn',
        VUE_APP_LAWCASE:'http://lawcase.tsatest.cn',
        VUE_APP_TSA:'https://www.tsa.cn',
        VUE_APP_VERIFY:'https://v.tsa.cn',
        VUE_APP_MEDIA:'http://media.tsa.cn/tsa',
        VUE_APP_NTSC:'http://www.ntsc.ac.cn',
        VUE_APP_BEIDOU:'http://www.beidou.gov.cn',
        VUE_APP_PKULAW:'https://www.pkulaw.com',
        VUE_APP_VEER:'https://www.veer.com',
        VUE_APP_BEIAN:'https://beian.miit.gov.cn/#/Integrated/index',
        VUE_APP_ANBEI:'http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010502045493',
        VUE_APP_EVGN:'http://ev.tsatest.cn/evidence',
        VUE_APP_TSA_QLWS:'https://www.tsa.cn/qlwsDownLoad',
        VUE_APP_TSA_PHONEUS:'https://www.tsa.cn/about',
    },
    pre: {
        VUE_APP_APIURL: 'http://website.tsapre.cn',
        VUE_APP_WEBSITE: 'http://website.tsapre.cn',
        VUE_APP_QLWS: 'https://tsa.soboten.com/chat/pc/v2/index.html?sysnum=05dcdaf7a8c2441aa325da0e40ea8b8a',
        VUE_media: 'http://media.tsa.cn/tsa',
        VUE_verify: 'https://verify-test.tsa.cn/',
        VUE_scp: 'http://scp.tsa.cn/',
        VUE_pkulaw: 'https://www.pkulaw.com/',
        VUE_baidu: 'https://xuper.baidu.com/case/econtract',
        VUE_jp: 'http://jp.tsa.cn/dist/page/index',
        VUE_tsa: 'http://usercenter.tsapre.cn/login',
        VUE_registration: 'https://usercenter.tsapre.cn/agreement/registration',
        VUE_privacy: 'http://usercenter.tsapre.cn/agreement/privacy',
        VUE_ntsc: 'http://www.ntsc.ac.cn/',
        VUE_beidou: 'http://www.beidou.gov.cn/',
        VUE_veer: 'https://www.veer.com/',
        VUE_beian: 'https://beian.miit.gov.cn/#/Integrated/index',
        VUE_APP_USERCENTERUI: 'http://usercenter.tsapre.cn',
        VUE_APP_ACCOUNT: 'http://account.tsapre.cn/',
        VUE_APP_ACCOUNT_M:'http://account-m.tsapre.cn/',
        VUE_Ev: 'http://ev.tsapre.cn/',
        VUE_icopyright: 'http://ipr.tsapre.cn/',
        VUE_1sign: 'http://pre.1sign.cn/',
        VUE_APP_EMAIL:'http://mail-proof-pre.tsa.cn/',
        VUE_APP_ANBEI: 'http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010502045493',
        VUE_APP_HOME: 'http://website-m.tsapre.cn/',
        VUE_APP_LAWCASE: 'http://lawcase.tsapre.cn/'
    },
    prod: {
        VUE_APP_APIURL: 'https://www.tsa.cn',
        VUE_APP_WEBSITE: 'https://www.tsa.cn',
        VUE_APP_QLWS: 'https://tsa.soboten.com/chat/pc/v2/index.html?sysnum=05dcdaf7a8c2441aa325da0e40ea8b8a',
        VUE_Ev: 'http://ev.tsa.cn/',
        VUE_icopyright: 'https://ipr.tsa.cn/',
        VUE_1sign: 'https://www.1sign.cn/',
        VUE_APP_EMAIL:'https://mail.tsa.cn/',
        VUE_media: 'http://media.tsa.cn/tsa',
        VUE_verify: 'https://v.tsa.cn/',
        VUE_scp: 'http://scp.tsa.cn/',
        VUE_pkulaw: 'https://www.pkulaw.com/',
        VUE_baidu: 'https://xuper.baidu.com/case/econtract',
        VUE_jp: 'http://jp.tsa.cn/dist/page/index',
        VUE_tsa: 'https://usercenter.tsa.cn/login',
        VUE_registration: 'https://usercenter.tsa.cn/agreement/registration?clientId=700012',
        VUE_privacy: 'https://usercenter.tsa.cn/agreement/privacy?clientId=700012',
        VUE_ntsc: 'http://www.ntsc.ac.cn/',
        VUE_beidou: 'http://www.beidou.gov.cn/',
        VUE_veer: 'https://www.veer.com/',
        VUE_beian: 'https://beian.miit.gov.cn/#/Integrated/index',
        VUE_APP_USERCENTERUI: 'http://usercenter.tsa.cn?clientId=700012',
        VUE_APP_ACCOUNT: 'http://account.tsa.cn/',
        VUE_APP_ACCOUNT_M:'http://account-m.tsa.cn/',
        VUE_APP_ANBEI: 'http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010502045493',
        VUE_APP_HOME: 'https://m.tsa.cn/',
        VUE_APP_LAWCASE: 'https://lawcase.tsa.cn/'
    },
}
